CREATE OR REPLACE TABLE results.test_average_scores AS
WITH CLASS_DATA AS (
  SELECT ID AS CLASS_ID,
         NAME AS CLASS_NAME,
         TEACHING_HOURS
  FROM `pyetl01.RawDataset.clean_class` AS CLASS
),
TEST_DATA AS (
  SELECT CLASS_ID,
         CREATED_AT AS TEST_CREATED_AT,
         AUTHORIZED_AT AS TEST_AUTHORIZED_AT,
         OVERALL_SCORE
  FROM `pyetl01.RawDataset.clean_test` AS TEST
  WHERE AUTHORIZED_AT IS NOT NULL and TEST_STATUS='SCORING_SCORED')
SELECT CLASS.CLASS_ID, CLASS.CLASS_NAME, CLASS.TEACHING_HOURS, TEST.TEST_CREATED_AT, TEST.TEST_AUTHORIZED_AT, AVG(TEST.OVERALL_SCORE) as AVG_CLASS_TEST_OVERALL_SCORE
FROM CLASS_DATA AS CLASS
INNER JOIN TEST_DATA AS TEST
ON CLASS.CLASS_ID = TEST.CLASS_ID
GROUP BY CLASS_ID, CLASS.CLASS_NAME, CLASS.TEACHING_HOURS, TEST.TEST_CREATED_AT, TEST.TEST_AUTHORIZED_AT
ORDER BY CLASS_ID