CREATE OR REPLACE TABLE results.test_utilization  AS
WITH CLASS_DATA AS (
  SELECT ID AS CLASS_ID,
         NAME AS CLASS_NAME,
         TEACHING_HOURS
  FROM `pyetl01.RawDataset.clean_class` AS CLASS
),
TEST_DATA AS (
  SELECT CLASS_ID,
         ID AS TEST_ID,
         CREATED_AT AS TEST_CREATED_AT,
         AUTHORIZED_AT AS TEST_AUTHORIZED_AT,
         TEST_LEVEL_ID AS TEST_LEVEL,
         row_number() OVER (PARTITION BY CLASS_ID ORDER BY ID ) AS class_test_number
  FROM `pyetl01.RawDataset.clean_test` AS TEST
  WHERE AUTHORIZED_AT IS NOT NULL)
SELECT CLASS.CLASS_ID, CLASS.CLASS_NAME, CLASS.TEACHING_HOURS, TEST.TEST_ID, TEST.TEST_CREATED_AT, TEST.TEST_AUTHORIZED_AT, TEST.TEST_LEVEL,         TEST.CLASS_TEST_NUMBER
FROM CLASS_DATA AS CLASS
INNER JOIN TEST_DATA AS TEST
ON CLASS.CLASS_ID = TEST.CLASS_ID
GROUP BY CLASS_ID, CLASS.CLASS_NAME, CLASS.TEACHING_HOURS, TEST.TEST_ID, TEST.TEST_CREATED_AT, TEST.TEST_AUTHORIZED_AT, TEST.TEST_LEVEL, TEST.CLASS_TEST_NUMBER
ORDER BY CLASS_ID